// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjE7-pufjWII1zUIYoATFigLbayJUk0uQ',
    appId: '1:102470524703:web:04f1a326d63343f1ffda2a',
    messagingSenderId: '102470524703',
    projectId: 'lets-chat-15d0a',
    authDomain: 'lets-chat-15d0a.firebaseapp.com',
    storageBucket: 'lets-chat-15d0a.firebasestorage.app',
    measurementId: 'G-YMGCCSGMBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqVbrvzC5OOKxRq07Nl-vnZ6lkZLPB9cw',
    appId: '1:102470524703:android:7275e2b52ec7b48cffda2a',
    messagingSenderId: '102470524703',
    projectId: 'lets-chat-15d0a',
    storageBucket: 'lets-chat-15d0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZPjISfjHuFktGWmbWkt-shyfBAMp9sec',
    appId: '1:102470524703:ios:f1d9476917856770ffda2a',
    messagingSenderId: '102470524703',
    projectId: 'lets-chat-15d0a',
    storageBucket: 'lets-chat-15d0a.firebasestorage.app',
    androidClientId: '102470524703-trou3j1fnkn6eluqrc15ah6jjloes3l3.apps.googleusercontent.com',
    iosClientId: '102470524703-kbi8g6ljq5ehf0iottaeu7kbkk1nge32.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZPjISfjHuFktGWmbWkt-shyfBAMp9sec',
    appId: '1:102470524703:ios:f1d9476917856770ffda2a',
    messagingSenderId: '102470524703',
    projectId: 'lets-chat-15d0a',
    storageBucket: 'lets-chat-15d0a.firebasestorage.app',
    androidClientId: '102470524703-trou3j1fnkn6eluqrc15ah6jjloes3l3.apps.googleusercontent.com',
    iosClientId: '102470524703-kbi8g6ljq5ehf0iottaeu7kbkk1nge32.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjE7-pufjWII1zUIYoATFigLbayJUk0uQ',
    appId: '1:102470524703:web:738c0db11bd9ab44ffda2a',
    messagingSenderId: '102470524703',
    projectId: 'lets-chat-15d0a',
    authDomain: 'lets-chat-15d0a.firebaseapp.com',
    storageBucket: 'lets-chat-15d0a.firebasestorage.app',
    measurementId: 'G-P10ZQT1HH3',
  );

}